### ISSUE TITLE
terminal widget problem

### ISSUE THREAD

**Issue by fredx181** [01micko/gtkdialog#87] opened 2020-05-29 09:14 UTC
When using terminal widget, on openbox, X crashes and on JWM, this error:  
```
(gtkdialog:28186): GLib-GObject-WARNING **: g_object_get_valist: object class 'VteTerminal' has no property named 'inner-border'

(gtkdialog:28186): Gdk-WARNING **: Native Windows wider or taller than 32767 pixels are not supported
The program 'gtkdialog' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 286 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

See here for suggestion from SFR for a fix:  
http://murga-linux.com/puppy/viewtopic.php?p=1059157#1059157   
Tested by using older **automaton.c** from before latest commits and it solves the problem for me.   

Fred

**Comment by 01micko** [comment] 2020-06-06 20:36
Hello @fredx181 

@woodenshoe-wi can you possibly fix this problem? 

Else I'll have to revert to the older automaton.c

**Comment by woodenshoe-wi** [comment] 2020-06-07 00:27
Maybe, I think I found the commit that broke it in libvte.

https://gitlab.gnome.org/GNOME/vte/-/commit/165b0cf9c40cddf

So I should just have to add another version check and use gtk_style_context_get_padding, but that should be for GTK3?

The inner-border property is still used by vte-0-36 but was switched to padding again in vte-0-38.

The deprecated vte_terminal_get_padding is still available in vte-0-36 so there isn’t really any need to use the inner-border property because it only lasted a little bit longer than vte_terminal_get_padding.

**Comment by 01micko** [comment] 2020-06-07 00:47
Thanks @woodenshoe-wi 

I'll wait and see.

**Comment by 01micko** [comment] 2020-06-08 05:37
Reported [here](http://murga-linux.com/puppy/viewtopic.php?p=1060293#1060293) that the problem is fixed, closing.

**Closed by 01micko** 2020-06-08 05:37 UTC

**Comment by woodenshoe-wi** [comment] 2020-06-08 23:08
I see a divergence in the source developing...

Wiak seems to have a fix for 'inner-border',  
http://www.murga-linux.com/puppy/viewtopic.php?p=1060379#1060379

but doesn’t seem to be too interested in Gtk+3 support.

I don’t consider myself to be the current gtkdialog developer, I just wanted to get Gtk+3 support working.  Since no good deed goes unpunished 😄 I don’t really want to make any changes myself that are not necessary for Gtk+3 support or bug fixes.

So I guess it is your call @01micko if you want wiak’s fix.  If you do, I think you will have to mention it, because wiak wrote:

> Since vte_terminal_get_padding() is considered fine by maintainer at 01micko legacy gtkdialog repo I won't push this change up there ...


On another subject, I have converted the gtkdialog wiki to GitHub format...  See https://github.com/01micko/gtkdialog/pull/83#issuecomment-385745505

Do you want to clone it to your personal account or the puppylinux-woof-CE account?
